### ISSUE TITLE
No web page loading

### ISSUE THREAD

**Issue by wuast94** [ich777/docker-magicmirror2#1]
i set all up and got no errors and the line: "Ready to go! Please point your browser to: http://0.0.0.0:8080"
but no web page is showing up :/ 

of course i use the right url. it was working before

**Comment by ich777** [comment]
@wuast94 what IP did you enter?

Have you got any other log output?

EDIT: is it possible that a module is causing this?

**Comment by wuast94** [comment]
OK don't know why but the port number was going up one number -.- now ist working fine :)
