### ISSUE TITLE
Module installation with modules.txt don't install some modules correctly

### ISSUE THREAD

**Issue by flemmingss** [ich777/docker-magicmirror2#4]
I have tried to get [MMM-CalendarExt3](https://github.com/MMRIZE/MMM-CalendarExt3) working for some days now, but I got an incomplete module. After some investigation, and some help from people at the MM forum it looks like the way the[ modules.txt](https://github.com/ich777/docker-magicmirror2/blob/master/modules.txt) and [start-server.sh](https://github.com/ich777/docker-magicmirror2/blob/master/scripts/start-server.sh) installs the modules it will not do so correctly. When I did the install procedure manually inside the container as described by the module author I got a complete working installation. 

Quoting [karsten13](https://forum.magicmirror.builders/user/karsten13) from the MM forum:

> The module installation is done via
> 
> `npm init -y`
> `npm install request --save`
> You have to ask the author of [this script](https://github.com/ich777/docker-magicmirror2/blob/master/scripts/start-server.sh) why he is doing this.
> 
> With this construction the postinstall/postupgrade scripts defined in the package,json of MMM-CalendarExt3 are never called so the CX3_Shared folder is empty.

Ref:
Se page 50 and 51 in [this thread](https://forum.magicmirror.builders/topic/16690/mmm-calendarext3/494?page=50).

**Comment by ich777** [comment]
Thanks for the report.
And in conclusion what needs to be changed? I don't use MagicMirror² anymore but I'm happy to make necessary changes and push a update.

**Comment by flemmingss** [comment]
> Thanks for the report. And in conclusion what needs to be changed? I don't use MagicMirror² anymore but I'm happy to make necessary changes and push a update.

Just has to refer to the thread, but how I understand it, the way your update-script is working it is not installing the submodule "CX3_Shared".

My working install was done like this:
```
root@413f2db9a7a6:/tmp# cd ..
root@413f2db9a7a6:/# cd magicmirror2/modules
root@413f2db9a7a6:/magicmirror2/modules# git clone https://github.com/MMRIZE/MMM-CalendarExt3
Cloning into 'MMM-CalendarExt3'...
remote: Enumerating objects: 301, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 301 (delta 65), reused 81 (delta 54), pack-reused 184
Receiving objects: 100% (301/301), 119.61 KiB | 1.21 MiB/s, done.
Resolving deltas: 100% (170/170), done.
root@413f2db9a7a6:/magicmirror2/modules# cd MMM-CalendarExt3
root@413f2db9a7a6:/magicmirror2/modules/MMM-CalendarExt3# npm install

> mmm-calendarext3@1.8.1 postinstall
> git submodule update --init --recursive

Submodule 'CX3_Shared' (https://github.com/MMRIZE/CX3_Shared) registered for path 'CX3_Shared'
Cloning into '/magicmirror2/modules/MMM-CalendarExt3/CX3_Shared'...
Submodule path 'CX3_Shared': checked out '44c7176e2b79a12e76badb78a49455bd7fbb22e3'

up to date, audited 1 package in 2s

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 10.2.3 -> 10.5.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.5.0
npm notice Run npm install -g npm@10.5.0 to update!
npm notice 
root@413f2db9a7a6:/magicmirror2/modules/MMM-CalendarExt3# git submodule update --init --recursive
root@413f2db9a7a6:/magicmirror2/modules/MMM-CalendarExt3# 
```

If you can't get it working, I suggest just putting a warning in the docker site/UnRAID add-on site, and in the modules.txt like:
**"This installation method is not compatible with all modules. If you are experience problems using this, try using the module's official installation instructions"**

**Comment by ich777** [comment]
> Just has to refer to the thread

Please update the container itself and try if it is now working.


> This installation method is not compatible with all modules.

This is just a note: this is the first module that I hear of that has issues installing and I surely can't guarantee that every installation is working when custom steps are needed (I tested a lot of modules back then when I created the container and all worked fine).

**Comment by ich777** [comment]
@flemmingss any update on this?

**Comment by ich777** [comment]
Closing due to no further response. Deprecated container now, however this issue should be solved with the latest update.
